---
services:
  lsp-zero-neovim:
    image: lsp-zero-neovim:latest
    container_name: lsp-zero-neovim
    ports:
      - "23333:2222"
    environment:
      - USERID=100                # optional
      - USERNAME=jason            # optional
      - PASSWORD=mysecretpassword # optional
      - PORT=2222                 # optional
      - PUBLICKEY=                # optional
      - PASSWORD_ACCESS=true      # optional
      - ROOT_PASSWORD=roottoor    # optional
      - SUDO_ACCESS=true          # optional
    restart: unless-stopped

